version: '3'
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: production_nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./client/build:/var/www/golinks
  #   ports:
  #     - 3333:80
  #   depends_on:
  #     - api
  nginx:
    build: ./client
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    #   - ./client/build:/var/www/golinks
    ports:
      - 3333:80
    depends_on:
      - api
  api:
    build: ./api
    depends_on:
      - mysql
  mysql:
    image: mysql:5.6
    environment:
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=golinks
    ports:
      - 3308:3306
